name: Deploy Module-S3_Buckets 

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'terraform/dev/**'
      - 'terraform/modules/s3_buckets/**'
      - '.github/workflows/deploy_s3_buckets.yml'

permissions:
  contents: read

jobs:
  terraform:
    name: Apply S3 Buckets Module
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-southeast-2
      TF_VAR_aws_region: ap-southeast-2
      TF_VAR_raw_bucket: insightflow-raw-bucket
      TF_VAR_clean_bucket: insightflow-clean-bucket

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/dev

      - name: Terraform Plan (S3 Buckets Only)
        run: terraform plan -input=false -target=module.s3_buckets
        working-directory: terraform/dev

      - name: Terraform Apply (S3 Buckets Only)
        run: terraform apply -auto-approve -target=module.s3_buckets
        working-directory: terraform/dev